# Generated by Django 5.0.1 on 2024-02-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=10)),
                ('cat_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=30)),
                ('student_password', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=30)),
                ('student_gradelevel', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('lessonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.lesson')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.BooleanField()),
                ('e_completion', models.BooleanField()),
                ('grade', models.FloatField()),
                ('enrollement_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course')),
                ('student_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.BooleanField()),
                ('grade', models.FloatField()),
                ('name', models.CharField(max_length=30)),
                ('lessonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.lesson')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
    ]
